sonar.organization=portolucaslp26
sonar.projectKey=coopervote-app
sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx,e2e/**,src/test/**,src/types/**
sonar.language=ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info